complete --command venv --exclusive --long help --description "Print help"
complete --command venv --exclusive --long version --description "Print version"
complete --command venv --exclusive --condition __fish_use_subcommand --arguments on --description "Activate virtual environment"
complete --command venv --exclusive --condition __fish_use_subcommand --arguments off --description "Deactivate virtual environment"
complete --command venv --exclusive --condition __fish_use_subcommand --arguments extras --description "List available extras"
complete --command venv --exclusive --condition __fish_use_subcommand --arguments enable --description "Enable extra"
complete --command venv --exclusive --condition __fish_use_subcommand --arguments disable --description "Disable extra"
